= REPL_OfficialNameFirstHalf_REPL: REPL_OfficialNameSecondHalf_REPL

Monorepo containing all material for *REPL_OfficialNameFirstHalf_REPL: REPL_OfficialNameSecondHalf_REPL* (aka REPL_OfficialAbbrev_REPL) that can reasonably be maintained in a Git repo.

image:https://github.com/mulesoft-consulting/training-template/workflows/Detect%20Dependency%20Updates/badge.svg[]
image:https://github.com/mulesoft-consulting/training-template/workflows/CI%20Solutions/badge.svg[]
image:https://github.com/mulesoft-consulting/training-template/workflows/Build%20Docs/badge.svg[]
image:https://github.com/mulesoft-consulting/training-template/workflows/Attach%20Assets%20to%20Release/badge.svg[]

== How to use this template repo to create a new course/cert repo

. In GitHub web UI:
.. Create new repo based on the https://github.com/mulesoft-consulting/training-template[training-template] template repo
.. Give https://github.com/orgs/mulesoft-consulting/teams/training-coursedev-team[training-coursedev-team] appropriate access
.. Set-up branch protection for `master*`
.. Add GitHub Secrets required by GitHub Actions workflows:
... `ENCRYPT_KEY`: the key used by Mule apps to decrypt secure (encryted) properties. If Mule apps in this monorepo use encrypted properties, then all of them use this same key for encrypting/decrypting them. The key needs at least 16 chars to be acceptible as an AES key
... `RELEASES_EE_USERNAME`: the username for an account with read-access to the MuleSoft EE Maven/Nexus repository
... `RELEASES_EE_PASSWORD`: the password for the username set in `RELEASES_EE_USERNAME`
... `REPO_PUSHER_USER_NAME`: the username name of a GitHub user that has repo permissions and hence can push to this repo. E.g., the username of the user performing this repo creation
... `REPO_PUSHER_USER_EMAIL`: the email of the GitHub user set in `REPO_PUSHER_USER_NAME`. Should be an email registered with that GitHub account
... `REPO_PUSHER_PERSONAL_ACCESS_TOKEN`: a personal access token with repo permissions of the GitHub user set in `REPO_PUSHER_USER_NAME`
. In local Git clone of the newly created repo:
.. Run and then remove `adapt-content-of-newly-created-repo.sh` after studying that script, e.g.:
+
[source,bash]
----
./adapt-content-of-newly-created-repo.sh training-APDevLevel2 "Anypoint Platform Development" "Production-Ready Development Practices" APDevPRDev devl2

rm adapt-content-of-newly-created-repo.sh
----
+
.. Rename this README section to "How this repo was set-up"
.. Commit and push
. In GitHub web UI:
.. Wait for GitHub Actions workflows to complete and related badges to appear green at the top of this README
.. Create a test GitHub Release
... Wait for GitHub Actions workflow to run and related badge to now also appear green at the top of this README
. In local Git clone: pull

=== Longer-term adaptions

. Remove or adapt the template content under `doc` and especially `doc/manual` to fit this course
. Adapt the template content in `release` to fit this course/cert:
.. Remove or adapt extensively `create-answer-references-asset.sh`
.. Remove or adapt extensively `create-correct-answers-asset.sh`
.. Remove or adapt extensively `create-student-manual-asset.sh`
.. Remove or adapt extensively `create-student-files-asset.sh`
. Adapt the GitHub Actions workflows in `.github/workflows` to fit this course/cert and the scripts in the `release` directory:
.. In particular, adapt extensively `attach-assets-to-release.yaml`
